### ISSUE TITLE
[FEAT] PresentationView

### ISSUE THREAD

**Issue by User-Lawn** [DeveloperAcademy-POSTECH/MC3-Team18-ForEllyJHealth#12]
### 구현해야하는 요소들
- Emoji Anim이 보여질 PresentationView 구현
- 현재 Peer를 받는 기기명 확인하는 View구현
- 6종의 Emoji의 Anim 구현
- UIKit 기반 App에 SwiftUI 연결

### 구현 방안
- UIHostingController -> UIKit 과 SwiftUI 연결
- ConfettiSwiftUI -> Emoji Anim
- MultipeerConnectivity -> Peer 확인
 
### TODO
- [x] PresentationView 구현
- [ ] Peer를 받는 기기명 확인하는 View구현
- [x] 6종의 Emoji의 Anim 구현
- [x] UIKit 기반 App에 SwiftUI 연결

### 비고 및 한계
-
