### ISSUE TITLE
[FEAT] Multipeer Connectivity 클래스 추가

### ISSUE THREAD

**Issue by jeong-hyeonHwang** [DeveloperAcademy-POSTECH/MC3-Team18-ForEllyJHealth#13]
### 구현해야하는 요소들
- 프로젝트 전반에 필요한 **Multipeer Connectivity와 관련된 클래스** 구현
- 위의 클래스에서 **부가적으로 필요한 Extension**
- 위의 클래스에서 **부가적으로 필요한 Constants**
---
### 구현 방안
**Multipeer Connectivity Class**
- **SessionPresenter**: 발표자 클래스
- **PresenterDetecto**r: 발표자 리스트 뷰 정보 갱신을 위한 발표자 추적 클래스
- **SessionAudience**: 청중 클래스

**Extension**
- 발표자, 발표자 탐지자을 구분하기 위한 접미사 제거를 위한 substring

**Constants**
- 발표자 구분 접미사
- 발표자 탐지자 구분 접미사
- 이모지 케이스 enum
- 이모지 enum -> String 변환 Method
---

### TODO
**Multipeer Connectivity Class**
- [x] SessionPresenter 작성
- [x] PresenterDetector 작성
- [x] SessionAudience 작성

**Extension**
- [x] substring

**Constants**
- [x] 발표자 구분 접미사
- [x] 발표자 탐지자 구분 접미사
- [x] 이모지 케이스 enum
- [x] 이모지 enum -> String 변환 Method

**Comment by jeong-hyeonHwang** [comment]
### 비고 및 한계 (2022.07.19)
- 발표자에 따라 방이 나누어지는 것이 아닌, 세션 내부에서 모든 peer는 하나의 네트워크 상에서 session이 만들어져서 invitePeer 및 intiveHandler(true, session) 동작 후 서로를 인지합니다
