### ISSUE TITLE
[FEAT] 회원가입 뷰 (예시)

### ISSUE THREAD

**Issue by jeong-hyeonHwang** [DeveloperAcademy-POSTECH/MC3-Team18-ForEllyJHealth#2]
**본 Issue는 예시입니다**

### 구현해야하는 요소들
-  회원가입의 전반적인 프로세스에 필요한 사항들을 구현해야한다
- 해당 이슈에서는 회원가입 뷰와 로그인 뷰 사이의 연결까지는 다루지 않습니다
- 해당 이슈에서는 이용약관 동의 및 휴대폰 인증에 관한 사항은 다루지 않습니다

### 구현 방안
**회원가입의 전반적인 프로세스**
_1. 이용약관 동의_
_2. 휴대폰 인증_
3. 이메일 입력
4. 아이디 입력 & 중복확인
5. 비밀번호 입력 & 재확인
6. 회원가입 버튼 클릭
- 3 to 6까지의 과정은 각각이 하나의 뷰를 구성합니다
- 3 to 6까지의 과정은 Navigation Link를 통해 View의 이동이 이루어집니다
 
### TODO
- [ ] 이메일 입력 창 만들기
- [ ] 비밀번호 입력 및 재확인 창 만들기
- [ ] 회원가입 버튼 만들기

### 비고 및 한계
**State Or Environment Object**
- **220713**: Navigation Link를 통한 이동 시 **State&Binding or Environment Object**를 쓸지에 대해 고민
- **220714**: 회원가입 프로세스는 로그인이 되어있는지에 대한 상태와 같이 앱의 전반에 영향을 미치지 않는 요소이기에 **State&Binding을 통해** 넘겨주는 형태로 확정
