### ISSUE TITLE
[FIX] Multipeer 세부 기능 관련 Fix 및 Refactor

### ISSUE THREAD

**Issue by jeong-hyeonHwang** [DeveloperAcademy-POSTECH/MC3-Team18-ForEllyJHealth#41]
### 구현해야하는 요소들
- Multipeer과 관련하여 발생하는 여러 버그 수정 및 Refactor

### 구현 방안
- 발생하는 버그 찾기
-> 같은 Emoji를 여러 번 빠륵게 터치하는 경우, 뷰가 갱신되지 않는다
- Refactor 리스트 작성
-> Emoji 전송 방식 수정
 
### TODO
- [x] 발생하는 버그 찾기
- [x] 버그1: 같은 Emoji 여러 번 빠르게 터치 시 뷰 갱신 X
- [x] Refactor 리스트 작성
- [x] 리팩1: Emoji 전송 방식 수정

### 비고 및 한계
** HOW TO?**
- **버그1 FIX**: 사용자가 Emoji를 보내는 경우 Emoji에 해당하는 데이터 이외에도 UUID를 함께 전송하여, 같은 Emoji라도 식별이 가능하도록 변경
-> Thanks to @skycat0212 👍
- **리팩1**: 버그1과 동일
