### ISSUE TITLE
[FEAT] Multipeer Connectivity 기능 추가

### ISSUE THREAD

**Issue by jeong-hyeonHwang** [DeveloperAcademy-POSTECH/MC3-Team18-ForEllyJHealth#43]
### 구현해야하는 요소들
- 새롭게 추가된 **질문 기능**과 **투표 기능**을 위한 요소 추가

### 구현 방안
- **질문 기능**
-> 데이터 구조
-> send Method
- **투표 기능**
-> 데이터 구조
-> send Method
 
### TODO
**질문기능**
- [ ] 데이터 구조 추가
- [ ] send Method 추가

**투표기능**
- [ ] 데이터 구조 추가
- [ ] send Method 추가

### 비고 및 한계
-

**Comment by jeong-hyeonHwang** [comment]
## About Question
**발표자의 경우**
- 청중으로부터 받은 질문을 모두 저장한다
- 단, 화면에 출력할 정보에서 식별자는 제외한다

**청중의 경우**
- Send Button을 누른 경우, 질문을 보낸다
- 단, 보내는 정보는 단순히 질문으로만 이루어지지 않고 식별자를 포함한다

### 구현해야하는 Methods
**SessionPresenter**
- Question Append

**SessionAudience**
- Send Question (with identifier)

**Comment by jeong-hyeonHwang** [comment]
## About Vote
**발표자의 경우**
- 청중으로부터 받은 투표 결과를 저장한다
- 단, 투표 결과의 반영은 투표 세션이 열려있을 때에 한해서 저장된다
- 위의 조건을 만족한 상황에서, 청중이 여러 번 투표를 한 경우, 가장 마지막 데이터가 반영된다
- 발표자는 청중으로부터 받은 투표 결과를 리셋 후 새로운 투표를 진행할 수 있다

**청중의 경우**
- 청중은 언제든지 투표를 보낼 수 있다
- 단, 보내는 정보는 단순히 투표에 대한 값만을 보내지 않고 식별자를 포함한다

### 구현해야하는 Methods
**SessionPresenter**
- Vote Append
-> 근데 이제 투표 세션이 열려있는지를 확인하는
-> 근데 이제 해당 PEER가 여러 번 보냈는지 확인하는
- Vote Clear

**SessionAudience**
- Send Vote (with identifier)

**Comment by jeong-hyeonHwang** [comment]
## 청중이 보낼 수 있는 정보
청중이 보낼 수 있는 **Data Type은 3가지**
- **Emoji**
- **Question**
- **Vote**

-> **위의 세 가지 케이스는 enum으로 관리한다**

### Vote+
청중이 보낼 수 있는 **Vote의 종류는 6가지**
- **YES**
- **NO**
- **Option 1**
- **Option 2**
- **Option 3**
- **Option 4**

-> **위의 6가지 케이스는 enum으로 관리한다**
