### ISSUE TITLE
[FEAT] Presentation View Custom Menu Button 추가

### ISSUE THREAD

**Issue by jeong-hyeonHwang** [DeveloperAcademy-POSTECH/MC3-Team18-ForEllyJHealth#52]
### 구현해야하는 요소들
- Presentation View 우상단에 Flip이 가능한 Button을 추가하자

### 구현 방안
- Button Customize 학습 후 적용하기
-> **Keyword: EXPANDED BUTTON!!!!!**
 
### TODO
- [x] Button Customize 공부
- [x] Button Customize 적용_PROTO
- [x] Text 한계값 설정하기
- [x] Device별 Padding, Frame 조절
- [x] 코드 점검 및 Refactor

### 비고 및 한계
-
