### ISSUE TITLE
[FEAT] Emoji 전송 시 Haptic 추가

### ISSUE THREAD

**Issue by jeong-hyeonHwang** [DeveloperAcademy-POSTECH/MC3-Team18-ForEllyJHealth#56]
### 구현해야하는 요소들
- 수행 중(Seq1): 사용자가 이모지를 보내기 위한 동작을 수행하고 있음을 전달해야한다
- 완료(Seq2): 사용자가 이모지를 보냈음을 전달해야한다
-> 발표에 집중하는 사용자(청중)를 위해 해당 요소들을 **Haptic을 통해 전달하자**

### 구현 방안
** Haptic의 형태**
**A안**
- Seq1: _징징징징징_ (연속성 부여)
- Seq2: _띵동_
**B안**
- Seq1: _딩_ (일회성)
- Seq2: _띵동_
 
### TODO
- [ ] Core Haptics Manager 가져오기
- [ ] A안 데이터 만들기
- [ ] B안 데이터 만들기
- [ ] 테스트를 위한 뷰 만들기

### 비고 및 한계
-
