### ISSUE TITLE
[FEAT] PresentationView Emoji Anim

### ISSUE THREAD

**Issue by User-Lawn** [DeveloperAcademy-POSTECH/MC3-Team18-ForEllyJHealth#57]
### 구현해야하는 요소들
- PresentationView Emoji Animation 수정 및 추가
- PresentationView Hi-Fi에 맞춰서 UI 적용
- Device UIScreen Size 에 맞춘 Anim Random Fix

### 구현 방안
- 폭죽 형태의 터지는 Anim 구현
- PresentationView 하단의 버튼 이모지 구현
- UIScreen extension 추가 및 적용
 
### TODO
- [x] PresentationView Emoji Animation 수정 및 추가하기
- [x] PresentationView Hi-Fi에 맞춰서 UI 적용
- [x] Device UIScreen Size 에 맞춘 Anim Random Fix

### 비고 및 한계
-
