### ISSUE TITLE
[FIX] Feedback 수정사항 반영

### ISSUE THREAD

**Issue by jeong-hyeonHwang** [DeveloperAcademy-POSTECH/MC3-Team18-ForEllyJHealth#83]
### 구현해야하는 요소들
- Feedback으로 요청받은 사항 구현 필요

### 구현 방안
- Text 수정 및 세부 디테일 구현
 
### TODO
- [x] 발표자 Alert Text 수정
- [x] Custom Menu CLOSE -> EXIT
- [x] 텍스트 영어로 수정 (메인 페이지 버튼, Custom Alert 영어로)
- [x] Presentation 하단 이모지 영역 색상 수정

### 비고 및 한계
-
