### ISSUE TITLE
[FEAT] 네비게이션 수정, safearea 하단 무시하고 패딩설정

### ISSUE THREAD

**Issue by song-cool** [DeveloperAcademy-POSTECH/MC3-Team18-ForEllyJHealth#94]
### 구현해야하는 요소들
- 네비게이션을 폴더방식으로 전부 수정

### 구현 방안
- 레이어 및 구조변경
- 
 
### TODO
- [ ] 네비게이션 구현위치 수정
- [ ] 네비게이션 상황에 맞게 수정
- [ ] 특수버튼 위치수정
- [ ] 리엑션뷰에서 뷰 위치 수정

### 비고 및 한계
-
